import Footer from "./components/footer";
import Navbar from "./components/navbar";
import "./globals.css";

export const metadata = {
  title: "ORPHEE DOWNLOADER",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black">
        <video autoPlay loop muted className="video-background">
          <source src="Vibing-in-the-Rain-4K.mp4" type="video/mp4" />
          Your browser does not support the video tag.
        </video>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
